### ISSUE TITLE
Does this hook support action2 in sails v1.0?

### ISSUE THREAD

**Issue by jinqiupeter** [theoomoregbee/sails-hook-swagger-generator#18]
It would be nice if we can extract information from the machine-as-action definition. what do you think @theo4u ?

**Comment by theo4u** [comment]
Yap nice, auto-generate the swagger information from it, I have been waiting for a way to do it, machine-as-action would do well now since the information about the function is within the action

Was thinking of a way to parse JSDoc #4 which was kinda a rabbit hole.

**Comment by theo4u** [comment]
Are you giving it a try  @jinqiupeter ?

**Comment by jinqiupeter** [comment]
@theo4u Not yet, I just wanted to check with you if it's currently supported, or if not supported it's still possible to add support for action2; but I can definitely try do that and submit PR!

**Comment by theo4u** [comment]
ok cool, expecting the PR, will go over this, this weekend

**Comment by marcoreni** [comment]
Hello @jinqiupeter , any update about this implementation?

**Comment by theo4u** [comment]
@marcoreni will add this to the roadmap for the next major release

**Comment by theoomoregbee** [comment]
yeah it does now, merged in #58
