### ISSUE TITLE
remove auto generated routes

### ISSUE THREAD

**Issue by bhaveshbheda** [theoomoregbee/sails-hook-swagger-generator#37]
i'm using sails 0.12 /1.0 
when i configure hook it generate all methods of controller in .json file ,
but i want only those routes which is in my congig/route.js file

**Comment by theo4u** [comment]
check here https://sailsjs.com/documentation/reference/configuration/sails-config-blueprints on how to disable default generated routes for your controller actions

**Comment by theoomoregbee** [comment]
see https://github.com/theoomoregbee/sails-hook-swagger-generator#configurations
