### ISSUE TITLE
Disable specific routes to generate

### ISSUE THREAD

**Issue by sanjayradadiya** [theoomoregbee/sails-hook-swagger-generator#51]
Hi Guys,

Can we disable some specific routes to generate in swagger?

Thanks

**Comment by danielsharvey** [comment]
Just a note that in https://github.com/theo4u/sails-hook-swagger-generator/pull/44 there is a configuration `includeRoute` which allows filtering of routes for inclusion in the generated Swagger.

See [Route Filtering](https://github.com/theo4u/sails-hook-swagger-generator/blob/f029159ac711ae08573a8923b0e1afe8eed77ff6/README.MD#route-filtering).

**Comment by theoomoregbee** [comment]
fixed in #58
