### ISSUE TITLE
auto generate tags for routes with model or just controllers

### ISSUE THREAD

**Issue by theoomoregbee** [theoomoregbee/sails-hook-swagger-generator#59]

**Comment by danielsharvey** [comment]
This should be covered in https://github.com/theoomoregbee/sails-hook-swagger-generator/pull/67.

Specifically:

1. Models have a default tag created based on `{globalId}`.
2. Controllers have a default tag created based on controller name without subdirectory (if any) or `Controller`. e.g. `subdir/NoModelController` --> `NoModel`
