### ISSUE TITLE
Unregconised shadow/implicit

### ISSUE THREAD

**Issue by jayemfonacier** [theoomoregbee/sails-hook-swagger-generator#76]
Encountering this issue.

![image](https://user-images.githubusercontent.com/39973224/84028776-e857b380-a9c3-11ea-801b-e37d94b30cc3.png)
 What seems to be the problem?

**Comment by danielsharvey** [comment]
It looks like there might be a problem analysing an association relationship. Are you able to give more information about the association in question?

**Comment by jayemfonacier** [comment]
Hi daniel,

Its a many-to-many relationship, here is the relationship between the two models,

User.js 
![image](https://user-images.githubusercontent.com/39973224/84034432-eb0ad680-a9cc-11ea-9f42-832543a84b45.png)

Permission.js
![image](https://user-images.githubusercontent.com/39973224/84034452-f1994e00-a9cc-11ea-98c5-c26f2000c4cd.png)

**Comment by jayemfonacier** [comment]
> Encountering this issue.
> 
> ![image](https://user-images.githubusercontent.com/39973224/84028776-e857b380-a9c3-11ea-801b-e37d94b30cc3.png)
> What seems to be the problem?

Heres the entire issue
`api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_permission_ids__permission_group_ids bound to middleware with unrecognised type 'BLUEPRINT: find' referencing unknown model group_permission_ids__permission_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_permission_ids__permission_group_ids/:id bound to middleware with unrecognised type 'BLUEPRINT: findone' referencing unknown model group_permission_ids__permission_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_permission_ids__permission_group_ids bound to middleware with unrecognised type 'BLUEPRINT: create' referencing unknown model group_permission_ids__permission_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_permission_ids__permission_group_ids/:id bound to middleware with unrecognised type 'BLUEPRINT: update' referencing unknown model group_permission_ids__permission_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_permission_ids__permission_group_ids/:id? bound to middleware with unrecognised type 'BLUEPRINT: destroy' referencing unknown model group_permission_ids__permission_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_permission_ids__permission_group_ids/:id bound to middleware with unrecognised type 'BLUEPRINT: update' referencing unknown model group_permission_ids__permission_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_permission_ids__permission_group_ids/:parentid/group_permission_ids bound to middleware with unrecognised type 'BLUEPRINT: populate' referencing unknown model group_permission_ids__permission_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_permission_ids__permission_group_ids/:parentid/permission_group_ids bound to middleware with unrecognised type 'BLUEPRINT: populate' referencing unknown model group_permission_ids__permission_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_user_ids__user_group_ids bound to middleware with unrecognised type 'BLUEPRINT: find' referencing unknown model group_user_ids__user_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_user_ids__user_group_ids/:id bound to middleware with unrecognised type 'BLUEPRINT: findone' referencing unknown model group_user_ids__user_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_user_ids__user_group_ids bound to middleware with unrecognised type 'BLUEPRINT: create' referencing unknown model group_user_ids__user_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_user_ids__user_group_ids/:id bound to middleware with unrecognised type 'BLUEPRINT: update' referencing unknown model group_user_ids__user_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_user_ids__user_group_ids/:id? bound to middleware with unrecognised type 'BLUEPRINT: destroy' referencing unknown model group_user_ids__user_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_user_ids__user_group_ids/:id bound to middleware with unrecognised type 'BLUEPRINT: update' referencing unknown model group_user_ids__user_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_user_ids__user_group_ids/:parentid/group_user_ids bound to middleware with unrecognised type 'BLUEPRINT: populate' referencing unknown model group_user_ids__user_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /group_user_ids__user_group_ids/:parentid/user_group_ids bound to middleware with unrecognised type 'BLUEPRINT: populate' referencing unknown model group_user_ids__user_group_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /permission_user_ids__user_permission_ids bound to middleware with unrecognised type 'BLUEPRINT: find' referencing unknown model permission_user_ids__user_permission_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /permission_user_ids__user_permission_ids/:id bound to middleware with unrecognised type 'BLUEPRINT: findone' referencing unknown model permission_user_ids__user_permission_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /permission_user_ids__user_permission_ids bound to middleware with unrecognised type 'BLUEPRINT: create' referencing unknown model permission_user_ids__user_permission_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /permission_user_ids__user_permission_ids/:id bound to middleware with unrecognised type 'BLUEPRINT: update' referencing unknown model permission_user_ids__user_permission_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /permission_user_ids__user_permission_ids/:id? bound to middleware with unrecognised type 'BLUEPRINT: destroy' referencing unknown model permission_user_ids__user_permission_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /permission_user_ids__user_permission_ids/:id bound to middleware with unrecognised type 'BLUEPRINT: update' referencing unknown model permission_user_ids__user_permission_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /permission_user_ids__user_permission_ids/:parentid/permission_user_ids bound to middleware with unrecognised type 'BLUEPRINT: populate' referencing unknown model
permission_user_ids__user_permission_ids
api_1    |  warn: WARNING: sails-hook-swagger-generator: Ignoring unregconised shadow/implicit route /permission_user_ids__user_permission_ids/:parentid/user_permission_ids bound to middleware with unrecognised type 'BLUEPRINT: populate' referencing unknown model
permission_user_ids__user_permission_ids`

**Comment by danielsharvey** [comment]
Would you please confirm the versions of:
- sails-hook-swagger-generator
- sails

**Comment by jayemfonacier** [comment]
hi its 1.2.4 for sails
![image](https://user-images.githubusercontent.com/39973224/84040295-08dc3980-a9d5-11ea-9d86-75735a28b810.png)

and ^3.1.2 for sails-hook-swagger-generator
![image](https://user-images.githubusercontent.com/39973224/84040355-1bef0980-a9d5-11ea-8774-b0ea4fcae076.png)

**Comment by danielsharvey** [comment]
Thanks. I will investigate some more.

**Comment by jayemfonacier** [comment]
> Thanks. I will investigate some more.

ok thanks!

**Comment by jayemfonacier** [comment]
@danielsharvey, hi using through association instead of many-to-many association helped solve my problem. nonetheless, thanks!

**Comment by danielsharvey** [comment]
@jayemfonacier I'm glad you got it working. 

I will still look into this more as I don't think the warnings should have occurred but I've not been able to reproduce as yet.

**Comment by jayemfonacier** [comment]
@danielsharvey, maybe its with the environment im working on, I wasn't able to reproduce the same errors when using just sails

**Comment by danielsharvey** [comment]
@jayemfonacier That is probably important. If you suspect/identify any feature/component/package that might affect this (in terms of reproducibility), let me know.

**Comment by jayemfonacier** [comment]
@danielsharvey, will do. thanks!
