### ISSUE TITLE
minor: Typo in repo description

### ISSUE THREAD

**Issue by danielsharvey** [theoomoregbee/sails-hook-swagger-generator#79]
In the repo description `OA3` should be `OAS`:
```
A tool to help generate Swagger specification documentation based on OA3 3.0 for Sails APIs
```

@theoomoregbee I can't update this :)

**Comment by theoomoregbee** [comment]
thanks, updated.

**Comment by danielsharvey** [comment]
@theoomoregbee Not sure if this was in several places, but the description is still `OA3` [here](https://github.com/theoomoregbee/sails-hook-swagger-generator):
![image](https://user-images.githubusercontent.com/12858056/85477974-f45f8a00-b5ed-11ea-8011-31d75f068c2c.png)

**Comment by theoomoregbee** [comment]
Oh! maybe the new UI didn't pick up the changes but will do it again
