### ISSUE TITLE
Custom action does not overwrite blueprint action documentation

### ISSUE THREAD

**Issue by OscarMeier** [theoomoregbee/sails-hook-swagger-generator#81]
My custom `user/create.js` action does not overwrite the blueprint action documentation.

I debugged your code and set the breakpoint at

https://github.com/theoomoregbee/sails-hook-swagger-generator/blob/846b80d2ec915f78bb925a2c7c9eaf2aab840325/lib/swagger-doc.ts#L73

The action is listed in the `controllers.actions` attribute:

```javascript
Object {actionType: "actions2", defaultTagName: "create", friendlyName: "Create", description: 
  "Create user.", inputs: Object, …}
  swagger-doc.js:106
  actionType:"actions2"
  defaultTagName:"create"
  description:"Create user."
  exits:Object {passwordNotMatch: Object, emailNotMatch: Object, emailAlreadyInUse: Object, …}
  fn:async function (inputs, exits) { … }
  friendlyName:"Create"
  globalId:"user/create.js"
  identity:"user/create.js"
  inputs:Object {first_name: Object, last_name: Object, email: Object, …}
```

But in the `routes` variable it is defined as "BLUEPRINT" instead of "ACTION" and it contains no information about the custom `user/create` action:

```javascript
Object {middlewareType: "BLUEPRINT", verb: "post", path: "/api/user", variables: Array(0), 
  optionalVariables: Array(0), …}
  swagger-doc.js:106
  action:"create"
  actionType:"blueprint"
  associationAliases:Array(0) []
  middlewareType:"BLUEPRINT"
  model:Object {globalId: "User", primaryKey: "id", identity: "user", …}
  optionalVariables:Array(0) []
  path:"/api/user"
  swagger:undefined
  variables:Array(0) []
  verb:"post"
}
```

Therefore the blueprint documentation is used in the result. It would be really great to use the integrated blueprint override functionality of sails. But, if this feature costs too much effort, I could also rename my action and add a custom route as a workaround.

**Comment by danielsharvey** [comment]
You're right: The resolution of `actions2` custom actions which override blueprint actions is not handled correctly. I can see how this needs to be improved.

**Comment by OscarMeier** [comment]
@danielsharvey Thank you for fixing this issue. Could you please publish the update on npm?

**Comment by danielsharvey** [comment]
> @danielsharvey Thank you for fixing this issue. Could you please publish the update on npm?

Working on it with @theoomoregbee - something has gone amiss with the release bot :(

**Comment by OscarMeier** [comment]
I tested your update and encountered three issues:

1. Custom model actions are not included anymore: Actions which don't overwrite blueprint actions are not included in the Swagger documentation (e.g. user/register).
2. The inputs of the overwritten blueprint actions are merged with the blueprint parameters: E.g. the overwritten find action displays all blueprint inputs (where, limit, skip, sort, ..).
3. Overwritten PATCH/POST blueprint actions consider the inputs as GET instead of request body parameters.

The first one is the most important. There are easy workarounds for the second and the third.

**Comment by danielsharvey** [comment]
Thanks @OscarMeier, appreciated. I will review and feed back.

**Comment by OscarMeier** [comment]
I don't exactly know why, but the custom model actions are included now. I didn't change the routes and I don't cache the swagger documentation. I will inform you if I encounter this issue again. But the second and the third issues are still remaining.

**Comment by danielsharvey** [comment]
Re 1. Custom model actions - confirming I think this works as expected.

See logout defined https://github.com/theoomoregbee/sails-hook-swagger-generator/blob/838e997b2c66d3d50c9c7237d7c753ae199cf4d9/api/controllers/UserController.js#L42-L43

produces output
https://github.com/theoomoregbee/sails-hook-swagger-generator/blob/8f9ba6888ddd427ce7a4f95bc52e67421b07d571/test/fixtures/generatedSwagger.json#L848-L850

Re 2. The inputs of the overwritten blueprint actions are merged with the blueprint parameters - this was intentional. See attached modified [UserController.js.txt](https://github.com/theoomoregbee/sails-hook-swagger-generator/files/4848913/UserController.js.txt) for example overwriting (see `create` and `find` actions). This issue I see is how to exclude defaults items from an overwritten blueprint action. Will think about this - one possible is treat explicit `null` values as 'exclude' during the merge. Let me know your thoughts.

Re 3. I think I see the issue - this occurs when the overwritten blueprint action changes the verb right? Would this be solved if we get the exclude working for 2 above?

**Comment by OscarMeier** [comment]
Re. 2. Okay, I see why it makes sense to merge blueprints parameters on controllers: You just have a `req` and a `res` parameter without further information. But actions are self-documenting and all the required and allowed inputs are predefined. Sails automatically excludes all parameters of the `req` object which are not included in the inputs of the action. Therefore I would suggest to differentiate controllers from actions. E.g. add the `user/create` action the same way you add the `user/logout` action to the Swagger documentation. That would also fix the third issue.

**Comment by danielsharvey** [comment]
Re 2: Back actions, I am taking you to mean the **actions2** actions are self-describing i.e. not all standalone actions. I still think that finding a way to optionally override the default documentation would still be a good outcome - I suspect that many cases for overriding the standard blueprint actions would be about overriding implementation whilst maintaining the interface contract (so the template documentation would apply). Let me know your thoughts.

Re 3: Irrespective of the above, I think the issue you raise is a good one. That is, the template blueprint documentation assumes the verb whereas it should perform some checks. Edge case, but perhaps worth checking.

**Comment by OscarMeier** [comment]
Re 2: Okey. Then it would be nice to have an option like the explicit null values to exclude parameters as you mentioned above (https://github.com/theoomoregbee/sails-hook-swagger-generator/issues/81#issuecomment-651468633).

Re 3: The action inputs of POST/PATCH actions are considered as query-parameters:

![sails-swagger-issue](https://user-images.githubusercontent.com/2379936/89538285-a946b280-d7fa-11ea-9d17-39f1e96b57cd.PNG)

`curl -X POST "http://localhost:1337/api/user?first_name=asd&last_name=asd&email=asd&confirm_email=asd&password=asdasdasdasd&confirm_password=asd&recaptcha=asd" -H "accept: application/json" -H "Content-Type: application/json" -H "X-CSRF-Token: fAp6UcyL-7CNl78UtVD_GDzYFcHv_mgE-O3Q" -d "{\"first_name\":\"string\",\"last_name\":\"string\",\"email\":\"user@example.com\",\"password\":\"string\",\"confirmed\":false,\"confirm_token\":\"string\",\"phone\":\"string\",\"stripe_id\":\"string\",\"img_url\":\"string\"}"`

The inputs should be in the request body of the curl call.

**Comment by danielsharvey** [comment]
Re 2: Thanks for the feedback. I will look to implement the exclude case.

Re 3: Thanks. I will investigate this more.
