### ISSUE TITLE
Removing default values

### ISSUE THREAD

**Issue by 0xGREG** [theoomoregbee/sails-hook-swagger-generator#94]
How do I make some default values hidden?

For example:
- externalDocs in blueprints
- License URL in config/swaggergenerator.js

For the latter I was able to make it `""` but that's not the proper way to work around it.

Thanks!

**Comment by theoomoregbee** [comment]
for license and externalDOcs we extend the configuration from OpenAPI configuration, so you can follow the instructions here to update it. https://github.com/theoomoregbee/sails-hook-swagger-generator#configurations

**Comment by 0xGREG** [comment]
I meant that if you leave out something like I don't declare a license URL in the config it'll show your default value that you set, and that kind of makes it annoying. I suggest removing default values that are optional from your code.

**Comment by theoomoregbee** [comment]
> I meant that if you leave out something like I don't declare a license URL in the config it'll show your default value that you set, and that kind of makes it annoying. I suggest removing default values that are optional from your code.

Oh yeah gotcha, will re-open this and make those changes today or tomorrow. Welcome a PRs too if you have the time

**Comment by theoomoregbee** [comment]
Tried this with a sample project. Don't think setting `url` of external docs to `""` is improper for now. If we get more concerns around this, then we can update the behaviour. 

```js
module.exports['swagger-generator'] = {
    disabled: false,
    swaggerJsonPath: './swagger/swagger.json',
    swagger: {
        openapi: '3.0.0',
		...
        externalDocs: {url: ''}
    },
	...
};
```
